### ISSUE TITLE
分词故障

### ISSUE THREAD

**Issue by pysio2007** [pysio2007/Vue-blog#25]
目前的分词依赖包在Netlify上有依赖问题= =
```
1:01:50 AM: error Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/build/repo/node_modules/nodejs-jieba/build/Release/jieba.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at file:///opt/build/repo/node_modules/nodejs-jieba/dist/index.mjs:1:257
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async loadUserConfig (file:///opt/build/repo/node_modules/@vuepress/cli/dist/index.js:77:18)
    at async CAC.<anonymous> (file:///opt/build/repo/node_modules/@vuepress/cli/dist/index.js:209:26)
```

**Comment by pysio2007** [comment]
在 1cc8b2d28468b1b30940e777252c963379bea44d 修复
